# Generated by Django 5.2.8 on 2025-11-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementsDataFloat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, db_column='datatime_db')),
                ('data_state', models.IntegerField(unique=True, verbose_name='state')),
                ('data_tag', models.CharField(max_length=25, verbose_name='tag')),
                ('data_value', models.FloatField(db_column='value', default=0)),
                ('data_unit', models.CharField(max_length=25, verbose_name='unit')),
            ],
            options={
                'verbose_name': 'Measurement',
                'verbose_name_plural': 'Measurements',
            },
        ),
    ]
