# Generated by Django 5.2.8 on 2025-11-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementsdatafloat',
            name='data_state',
            field=models.IntegerField(db_column='state', default=0),
        ),
        migrations.AlterField(
            model_name='measurementsdatafloat',
            name='data_tag',
            field=models.CharField(db_column='tag', max_length=25),
        ),
        migrations.AlterField(
            model_name='measurementsdatafloat',
            name='data_unit',
            field=models.CharField(db_column='unit', max_length=25),
        ),
    ]
